K:   [375.98849,  0.   ,428.,
      0.     ,375.98849,240.,
      0.     ,  0.   ,  1.   ]
p0: [2., -1.,2., 1.9708,
     1., -1.,2., 1.9708,
     2., -1.,1., 1.9708,
     1., -1.,1., 1.9708]

frequency: 30.
robot_name_prefix: "parrot_bebop_2"
takeoff_threshold: 0.05
landing_threshold: 0.03
hover_height: 1.5
gain_takeoff: .5

polar: false
gain: .2
gain_w: 1.
img_depth: 4.

save_log: true
output: /home/bloodfield/ros-rolling/Workspaces/bebop/src/ros2_bebop_ibvs/output
