#   Drone definitions
model: "parrot_bebop_2_custom"  # gazebo model name
robot_name: "parrot_bebop_2"
K:   [375.98849,  0.   ,428.,
      0.     ,375.98849,240.,
      0.     ,  0.   ,  1.   ]
CamR: [0.,-1., 0.,
      -1., 0., 0.,
       0., 0.,-1.]
CamT: [0., 0., -0.05]

#   Conditions
n_agents: 4
pd: [0., -1.,2., 0,
     1., -1.,2., 0,
     0.,  1.,2., 0,
     1.,  1.,2., 0]


# tracking_matchImg0_04
# p0: [-0.5, -0.8, 2.5,    0,
#        1.,  -1.,  2., -0.1,
#      -0.2,   1., 2.5,  0.1,
#        1.,  1.2,  2.,    0]
# L: [0, 1, 1, 1,
#     1, 0, 1, 1,
#     1, 1, 0, 1,
#     1, 1, 1, 0]


# # tracking2_matchImg0_01
# p0: [ 0.1, -1., 2.5,    0,
#       0.9, -1., 2.3, -0.1,
#       -0.1, 0.9, 2.3, 0.1,
#       1.,  1.,  2.5,    0]
#
# L: [0, 1, 1, 0,
#     1, 0, 0, 1,
#     1, 0, 0, 1,
#     0, 1, 1, 0]

# # tracking2_matchImg0_02
# p0: [ 0.2, -1., 2.5,    0,
#       0.8, -0.8, 2.3, -0.1,
#       0.1, 0.8, 2.3, 0.1,
#       1.,  0.8,  2.5,    0]
#
# L: [0, 1, 1, 0,
#     1, 0, 0, 1,
#     1, 0, 0, 1,
#     0, 1, 1, 0]
# tracking2_matchImg0_02
p0: [ 0.2, -1., 2.5,    0,
      0.8, -0.8, 2.3, 0.1,
      0.1, 0.8, 2.3, -0.2,
      0.8,  0.8,  2.5,    0]

L: [0, 1, 1, 0,
    1, 0, 0, 1,
    1, 0, 0, 1,
    0, 1, 1, 0]

# Simulation
frequency: 30.
save_log: false
output: /home/axolomancer/workspaces/ibvs-formation/src/ros2_bebop_ibvs/output

#   Control
control: "mav_ibvs_direct_tracking_sim"
# control: "mav_ibvs_direct_matching_sim"
gain: .1
# gain: .08
gain_w: 1.
# gain_w: 1.2
img_depth: 2.3
polar: false



# --------------------------------------------------------
#   Image Proc
# --------------------------------------------------------

#    Feature based
world: "ground.world"

nfeatures: 100
scaleFactor: 1.2
nlevels: 8
edgeThreshold: 15
patchSize: 30
fastThreshold: 20
flann_ratio: 0.7
# flann_ratio: 0.6
detect_threshold: 12
matcher_threshold: 6
ref_prefix: "reference_ground"


# --------------------------------------------------------

  # Aruco based
# world: "ground_and_arucos.world"
# imageProc: "arucos"
aruco_dictionary: 4X4_1000

adaptiveThreshWinSizeMin: 141
adaptiveThreshWinSizeMax: 251
adaptiveThreshWinSizeStep: 20
adaptiveThreshConstant: 4
perspectiveRemovePixelPerCell: 10
perspectiveRemoveIgnoredMarginPerCell: 0.2
# ref_image: ground_reference_arucos.png

# --------------------------------------------------------
#   PLOT CONFIGURATION
# --------------------------------------------------------

system: mav
point_type: features
# type: arucos

vel_limits: [-0.15, 0.15]
error_limits: [-1, 1]
camera_angle: pi
